"""Local AI thumbnail bank with a strict text-free asset contract.

The bank stores images generated by the local image model.  The renderer never
adds a title, badge, watermark, or other typography; title metadata is used only
for deterministic asset selection.
"""
from __future__ import annotations

import hashlib
import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from PIL import Image

_IMAGE_EXTENSIONS = frozenset({".jpg", ".jpeg", ".png", ".webp"})
_REJECTED_NAME_TOKENS = frozenset(
    {"text", "title", "caption", "subtitle", "watermark", "logo", "badge", "overlay"}
)


@dataclass(frozen=True)
class LocalThumbnailAsset:
    path: Path
    source: str
    text_free: bool = True


class LocalAIThumbnailBank:
    """Resolve a generated, local, text-free thumbnail asset deterministically."""

    def __init__(self, root: Optional[Path | str] = None) -> None:
        configured = root or os.environ.get("AI_THUMBNAIL_BANK_DIR")
        self.root = Path(configured) if configured else Path("assets/thumbnails/ai_bank")
        if not self.root.is_absolute():
            self.root = Path(__file__).resolve().parents[3] / self.root
        self.root = self.root.resolve()

    @staticmethod
    def _name_is_clean(path: Path) -> bool:
        tokens = set(path.stem.lower().replace("-", "_").split("_"))
        return not tokens.intersection(_REJECTED_NAME_TOKENS)

    @staticmethod
    def _sidecar(path: Path) -> Optional[dict]:
        sidecar = path.with_suffix(path.suffix + ".json")
        if not sidecar.is_file():
            return None
        try:
            data = json.loads(sidecar.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            return None
        return data if isinstance(data, dict) else None

    @classmethod
    def is_text_free(cls, path: Path) -> bool:
        """Validate the bank declaration and image readability without OCR guessing."""
        if path.suffix.lower() not in _IMAGE_EXTENSIONS or not cls._name_is_clean(path):
            return False
        metadata = cls._sidecar(path)
        if metadata is not None and metadata.get("text_free") is not True:
            return False
        try:
            with Image.open(path) as image:
                image.verify()
        except (OSError, ValueError):
            return False
        return True

    def candidates(self, *, channel_id: str = "", archetype: str = "") -> list[Path]:
        """Return text-free AI assets from the most specific local folders first."""
        if not self.root.is_dir():
            return []
        keys = [str(channel_id).strip().lower(), str(archetype).strip().lower()]
        folders: list[Path] = []
        for key in keys:
            if key:
                folders.append(self.root / key)
        folders.append(self.root)
        found: list[Path] = []
        for folder in folders:
            if not folder.is_dir():
                continue
            for path in sorted(folder.rglob("*")):
                if path.is_file() and path not in found and self.is_text_free(path):
                    found.append(path)
        return found

    def resolve(
        self,
        *,
        channel_id: str = "",
        archetype: str = "",
        selection_key: str = "",
    ) -> Optional[LocalThumbnailAsset]:
        candidates = self.candidates(channel_id=channel_id, archetype=archetype)
        if not candidates:
            return None
        digest = hashlib.sha256(
            f"{channel_id}|{archetype}|{selection_key}".encode("utf-8")
        ).digest()
        selected = candidates[int.from_bytes(digest[:8], "big") % len(candidates)]
        return LocalThumbnailAsset(path=selected, source="local_ai_bank")

    @staticmethod
    def write_manifest_entry(path: Path, *, prompt_id: str = "local") -> Path:
        """Record the text-free gate next to a generated asset for auditability."""
        sidecar = path.with_suffix(path.suffix + ".json")
        sidecar.write_text(
            json.dumps({"text_free": True, "generator": "local_ai", "prompt_id": prompt_id}, indent=2),
            encoding="utf-8",
        )
        return sidecar
