"""src/scrapers - Modular story scrapers, multi-source ingestion, and queue replenishers."""

from __future__ import annotations

from src.scrapers.common import (
    AsyncRateLimiter,
    _async_backoff_sleep,
    _is_mocked_requests,
    _run_sync,
    _to_float,
    _to_int,
)
from src.scrapers.local import (
    PRESET_CANONICAL_STORIES,
    _load_canonical_stories,
    _parse_frontmatter,
)
from src.scrapers.models import ScrapedStory
from src.scrapers.reddit import (
    CHANNEL_SUBREDDITS,
    DEFAULT_USER_AGENT,
    USER_AGENTS,
    _PULLPUSH_LIMITER,
    _REDDIT_LIMITER,
    _env_min_score,
    _env_min_upvote_ratio,
    _extract_posts_from_json,
    _fetch_url_aiohttp,
    _fetch_url_mocked_requests,
    _is_deleted_or_removed,
    async_fetch_reddit_stories,
    fetch_reddit_stories,
    is_high_quality_story,
)
from src.scrapers.replenisher import (
    _LANE_REPLENISH_BACKOFF,
    async_ensure_queue_depth,
    async_replenish_queue,
    ensure_queue_depth,
    replenish_queue,
)
from src.scrapers.scp import (
    CANONICAL_SCP_STORIES,
    CROM_GRAPHQL_ENDPOINT,
    DEFAULT_LICENSE,
    SCP_WIKI_BASE_URL,
    SCP_WIKI_ES_BASE_URL,
    _CROM_RATE_LIMITER,
    _WIKIDOT_RATE_LIMITER,
    _WikidotHTMLCleaner,
    async_fetch_scp_by_item,
    async_fetch_top_scp_articles,
    async_fetch_top_scp_from_crom,
    async_scrape_and_enqueue_scp,
    fetch_scp_by_item,
    fetch_top_scp_articles,
    fetch_top_scp_from_crom,
    parse_scp_text,
    parse_scp_wikidot_html,
    scrape_and_enqueue_scp,
)

__all__ = [
    "ScrapedStory",
    "AsyncRateLimiter",
    "_run_sync",
    "_to_int",
    "_to_float",
    "_async_backoff_sleep",
    "_is_mocked_requests",
    "DEFAULT_USER_AGENT",
    "USER_AGENTS",
    "CHANNEL_SUBREDDITS",
    "_env_min_score",
    "_env_min_upvote_ratio",
    "_is_deleted_or_removed",
    "is_high_quality_story",
    "_REDDIT_LIMITER",
    "_PULLPUSH_LIMITER",
    "_extract_posts_from_json",
    "_fetch_url_aiohttp",
    "_fetch_url_mocked_requests",
    "async_fetch_reddit_stories",
    "fetch_reddit_stories",
    "PRESET_CANONICAL_STORIES",
    "_parse_frontmatter",
    "_load_canonical_stories",
    "DEFAULT_LICENSE",
    "CROM_GRAPHQL_ENDPOINT",
    "SCP_WIKI_BASE_URL",
    "SCP_WIKI_ES_BASE_URL",
    "CANONICAL_SCP_STORIES",
    "_WikidotHTMLCleaner",
    "parse_scp_text",
    "parse_scp_wikidot_html",
    "_CROM_RATE_LIMITER",
    "_WIKIDOT_RATE_LIMITER",
    "async_fetch_top_scp_from_crom",
    "fetch_top_scp_from_crom",
    "async_fetch_scp_by_item",
    "fetch_scp_by_item",
    "async_fetch_top_scp_articles",
    "fetch_top_scp_articles",
    "async_scrape_and_enqueue_scp",
    "scrape_and_enqueue_scp",
    "_LANE_REPLENISH_BACKOFF",
    "async_replenish_queue",
    "replenish_queue",
    "async_ensure_queue_depth",
    "ensure_queue_depth",
]
