"""SQLite repository with versioned migrations, leases and publication proofs.

Backward-compatible facade delegating execution to the modular src.core.repository package.
"""

from __future__ import annotations

from src.core.repository import (
    ALL_STATUSES,
    BUSY_TIMEOUT_MS,
    CanonicalChannel,
    JobStatus,
    LoopCatalogRepository,
    LoopRecord,
    MIGRATION_001,
    MIGRATION_003,
    MIGRATION_004,
    MIGRATION_005,
    MigrationReport,
    PublicationProof,
    QueueRepository,
    _add_story_columns,
    _apply_migration_005,
    _count_channels,
    _ensure_legacy_stories,
    _migration_checksum,
    _utc_now,
    backup_database,
    canonical_channel,
    compute_file_sha256,
    compute_simhash_64,
    connect,
    hamming_distance_64,
    is_simhash_duplicate,
    migrate_database,
    read_daemon_heartbeat,
    re_full_sha256,
    resolve_loop_file_path,
    simhash_hamming_distance,
    to_signed_64,
    to_unsigned_64,
    touch_daemon_liveness,
    validate_db_path,
    wal_checkpoint_passive,
)

__all__ = [
    "QueueRepository",
    "MigrationReport",
    "BUSY_TIMEOUT_MS",
    "validate_db_path",
    "connect",
    "wal_checkpoint_passive",
    "migrate_database",
    "backup_database",
    "touch_daemon_liveness",
    "read_daemon_heartbeat",
    "to_signed_64",
    "to_unsigned_64",
    "compute_simhash_64",
    "simhash_hamming_distance",
    "hamming_distance_64",
    "is_simhash_duplicate",
    "re_full_sha256",
    "ALL_STATUSES",
    "CanonicalChannel",
    "JobStatus",
    "PublicationProof",
    "canonical_channel",
    "MIGRATION_001",
    "MIGRATION_003",
    "MIGRATION_004",
    "MIGRATION_005",
    "_utc_now",
    "_migration_checksum",
    "_ensure_legacy_stories",
    "_add_story_columns",
    "_apply_migration_005",
    "_count_channels",
]
