"""
src/core/scoring.py - Backward-compatible facade for src.core.scoring.

Re-exports all data contracts, heuristics, semantic evaluators, and hybrid scoring coordinators.
"""
from __future__ import annotations

from src.core.scoring import (
    DEFAULT_ALPHA,
    DEFAULT_HEURISTIC_THRESHOLD,
    DEFAULT_HYBRID_THRESHOLD,
    DEFAULT_SEMANTIC_THRESHOLD,
    HeuristicScoreReport,
    SemanticScoreReport,
    StoryScoringVerdict,
    _CONFLICT_PATTERNS,
    _CURIOSITY_PATTERNS,
    _DRAMA_PATTERNS,
    _ESCALATION_PATTERNS,
    _HORROR_PATTERNS,
    _IRONY_PATTERNS,
    _NEGATIVE_GREETING_PATTERNS,
    _NEGATIVE_PREAMBLE_PATTERNS,
    _POSITIVE_IN_MEDIAS_RES,
    _POSITIVE_QUESTION_PATTERNS,
    _POSITIVE_STAKES_PATTERNS,
    _POSITIVE_TENSION_KEYWORDS,
    _TWIST_PATTERNS,
    _build_semantic_eval_prompt,
    _build_semantic_report_from_llm,
    _evaluate_semantic_deterministically,
    _extract_story_fields,
    _normalize_hook_text,
    _parse_llm_json_response,
    _strip_accents,
    async_evaluate_semantic_viral_potential,
    async_filter_and_score_story,
    compute_hybrid_story_score,
    detect_opening_hook_strength,
    estimate_spoken_seconds,
    evaluate_fast_heuristics,
    evaluate_retention_length_score,
    evaluate_semantic_viral_potential,
    filter_and_score_story,
    first_spoken_hook,
    opening_hook_within_budget,
)

__all__ = [
    "DEFAULT_ALPHA",
    "DEFAULT_HEURISTIC_THRESHOLD",
    "DEFAULT_HYBRID_THRESHOLD",
    "DEFAULT_SEMANTIC_THRESHOLD",
    "HeuristicScoreReport",
    "SemanticScoreReport",
    "StoryScoringVerdict",
    "_CONFLICT_PATTERNS",
    "_CURIOSITY_PATTERNS",
    "_DRAMA_PATTERNS",
    "_ESCALATION_PATTERNS",
    "_HORROR_PATTERNS",
    "_IRONY_PATTERNS",
    "_NEGATIVE_GREETING_PATTERNS",
    "_NEGATIVE_PREAMBLE_PATTERNS",
    "_POSITIVE_IN_MEDIAS_RES",
    "_POSITIVE_QUESTION_PATTERNS",
    "_POSITIVE_STAKES_PATTERNS",
    "_POSITIVE_TENSION_KEYWORDS",
    "_TWIST_PATTERNS",
    "_build_semantic_eval_prompt",
    "_build_semantic_report_from_llm",
    "_evaluate_semantic_deterministically",
    "_extract_story_fields",
    "_normalize_hook_text",
    "_parse_llm_json_response",
    "_strip_accents",
    "async_evaluate_semantic_viral_potential",
    "async_filter_and_score_story",
    "compute_hybrid_story_score",
    "detect_opening_hook_strength",
    "estimate_spoken_seconds",
    "evaluate_fast_heuristics",
    "evaluate_retention_length_score",
    "evaluate_semantic_viral_potential",
    "filter_and_score_story",
    "first_spoken_hook",
    "opening_hook_within_budget",
]
