"""src/sanitizer - Modular Script Sanitizer & System Prompt Leak Cleaner Engine.

Backward-compatible package re-exporting all sanitizer modules and contracts.
"""

from __future__ import annotations

import logging

from src.sanitizer.editorial import (
    _COMPILED_EDITORIAL_CACHE,
    _FILE_RULES_CACHE,
    _SENTENCE_SPLIT,
    CRINGE_INTRO_PATTERNS,
    FORBIDDEN_EDITORIAL_PATTERNS,
    LEGACY_BRANDING_PATTERNS,
    MARKDOWN_HEADER_PREAMBLE,
    POSTAMBLE_PATTERNS,
    PREAMBLE_PATTERN,
    _editorial_patterns,
    _get_compiled_editorial_patterns,
    check_forbidden_editorial_elements,
    repair_forbidden_editorial,
    sanitize_llm_script,
    sanitize_script_text,
    suppress_title_repetition,
)
from src.sanitizer.filesystem import sanitize_filename
from src.sanitizer.hashing import (
    compute_simhash_64,
    evaluate_script_simhash,
    hamming_distance_64,
)
from src.sanitizer.linguistic import (
    SPANGLISH_REPLACEMENTS,
    TextSanitizer,
    filter_orphan_english_blocks,
    normalize_spanglish_terms,
    sanitize_html_entities,
    sanitize_text,
)
from src.sanitizer.security import (
    PROMPT_LEAK_PATTERNS,
    TABOO_BARRIER_PATTERNS,
    PromptLeakError,
    extract_script_from_reasoning,
    strip_llm_prompt_leaks,
    validate_semantic_barrier,
)
from src.sanitizer.tts import (
    ORDINAL_OR_ROMAN,
    RE_ACT_CHAPTER_LABELS,
    RE_ACT_CHAPTER_LINE,
    RE_ASS_TAGS,
    RE_CHAPTER_HEADER_LINE,
    RE_CODE_BLOCKS,
    RE_EDITORIAL_CUES,
    RE_MARKDOWN_BOLD,
    RE_MARKDOWN_CHARS,
    RE_MARKDOWN_CHARS_ALL,
    RE_MARKDOWN_HEADERS,
    RE_MARKDOWN_ITALIC,
    RE_MARKDOWN_LINKS,
    RE_SFX_CUES,
    RE_SFX_INLINE,
    RE_SFX_LINE,
    RE_STRUCTURAL_HEADERS_INLINE,
    RE_STRUCTURAL_HEADERS_LINE,
    RE_STRUCTURAL_HEADERS_PREFIX,
    RE_TITLE_INLINE,
    RE_TITLE_PREFIX,
    RE_URLS,
    limpiar_texto_para_tts,
    sanitize_scp_acronyms_for_tts,
    standardize_timestamp_format,
    strip_act_chapter_headers,
    strip_ass_tags,
    validate_beat_format,
    validate_pre_tts_script,
)

logger = logging.getLogger("sanitizer")

__all__ = [
    "logger",
    "PromptLeakError",
    "TABOO_BARRIER_PATTERNS",
    "ORDINAL_OR_ROMAN",
    "RE_ASS_TAGS",
    "RE_CODE_BLOCKS",
    "RE_MARKDOWN_LINKS",
    "RE_URLS",
    "RE_MARKDOWN_HEADERS",
    "RE_MARKDOWN_BOLD",
    "RE_MARKDOWN_ITALIC",
    "RE_MARKDOWN_CHARS",
    "RE_MARKDOWN_CHARS_ALL",
    "RE_STRUCTURAL_HEADERS_PREFIX",
    "RE_STRUCTURAL_HEADERS_LINE",
    "RE_STRUCTURAL_HEADERS_INLINE",
    "RE_CHAPTER_HEADER_LINE",
    "RE_TITLE_PREFIX",
    "RE_TITLE_INLINE",
    "RE_ACT_CHAPTER_LABELS",
    "RE_ACT_CHAPTER_LINE",
    "RE_EDITORIAL_CUES",
    "RE_SFX_CUES",
    "RE_SFX_LINE",
    "RE_SFX_INLINE",
    "strip_ass_tags",
    "strip_act_chapter_headers",
    "sanitize_scp_acronyms_for_tts",
    "validate_semantic_barrier",
    "validate_pre_tts_script",
    "PROMPT_LEAK_PATTERNS",
    "LEGACY_BRANDING_PATTERNS",
    "CRINGE_INTRO_PATTERNS",
    "FORBIDDEN_EDITORIAL_PATTERNS",
    "_editorial_patterns",
    "_get_compiled_editorial_patterns",
    "check_forbidden_editorial_elements",
    "_SENTENCE_SPLIT",
    "repair_forbidden_editorial",
    "PREAMBLE_PATTERN",
    "MARKDOWN_HEADER_PREAMBLE",
    "POSTAMBLE_PATTERNS",
    "sanitize_llm_script",
    "sanitize_html_entities",
    "filter_orphan_english_blocks",
    "sanitize_script_text",
    "SPANGLISH_REPLACEMENTS",
    "normalize_spanglish_terms",
    "suppress_title_repetition",
    "TextSanitizer",
    "sanitize_text",
    "standardize_timestamp_format",
    "limpiar_texto_para_tts",
    "validate_beat_format",
    "extract_script_from_reasoning",
    "strip_llm_prompt_leaks",
    "sanitize_filename",
    "compute_simhash_64",
    "hamming_distance_64",
    "evaluate_script_simhash",
    "_FILE_RULES_CACHE",
    "_COMPILED_EDITORIAL_CACHE",
]
