import os
import time
import json
import tempfile
import pytest
from pathlib import Path
from src.core.cookies import (
    SessionStatus,
    SessionHealthResult,
    parse_cookies_file,
    format_cookies_for_playwright,
    validate_youtube_session_cookies,
)


def test_parse_json_cookies_array(tmp_path):
    cookie_file = tmp_path / "cookies.json"
    sample = [
        {
            "name": "LOGIN_INFO",
            "value": "AFmmF2kwRQ...token",
            "domain": ".youtube.com",
            "path": "/",
            "expires": time.time() + 86400 * 30,
            "httpOnly": True,
            "secure": True,
            "sameSite": "None",
        },
        {
            "name": "SID",
            "value": "sid_sample_value",
            "domain": ".google.com",
            "path": "/",
            "expirationDate": time.time() + 86400 * 30,
            "httpOnly": False,
            "secure": True,
            "sameSite": "lax",
        },
    ]
    cookie_file.write_text(json.dumps(sample), encoding="utf-8")

    cookies = parse_cookies_file(cookie_file)
    assert len(cookies) == 2
    assert cookies[0]["name"] == "LOGIN_INFO"
    assert cookies[0]["value"] == "AFmmF2kwRQ...token"
    assert cookies[0]["domain"] == ".youtube.com"
    assert cookies[0]["secure"] is True
    assert cookies[0]["httpOnly"] is True
    assert cookies[1]["name"] == "SID"
    assert cookies[1]["expires"] > time.time()


def test_parse_netscape_cookies_file(tmp_path):
    cookie_file = tmp_path / "cookies.txt"
    future_expiry = int(time.time() + 86400 * 15)
    content = f"""# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by yt-dlp

.youtube.com	TRUE	/	TRUE	{future_expiry}	LOGIN_INFO	netscape_login_token_val
.google.com	TRUE	/	TRUE	{future_expiry}	__Secure-1PSID	secure_1psid_val
.youtube.com	TRUE	/	FALSE	{future_expiry}	PREF	f4=4000000
"""
    cookie_file.write_text(content, encoding="utf-8")

    cookies = parse_cookies_file(cookie_file)
    assert len(cookies) == 3
    names = [c["name"] for c in cookies]
    assert "LOGIN_INFO" in names
    assert "__Secure-1PSID" in names
    assert "PREF" in names

    login_c = next(c for c in cookies if c["name"] == "LOGIN_INFO")
    assert login_c["value"] == "netscape_login_token_val"
    assert login_c["domain"] == ".youtube.com"
    assert login_c["secure"] is True
    assert login_c["expires"] == float(future_expiry)


def test_parse_cookies_missing_file():
    with pytest.raises(FileNotFoundError):
        parse_cookies_file("/non/existent/path/cookies.json")


def test_parse_cookies_empty_or_invalid_file(tmp_path):
    empty_file = tmp_path / "empty.json"
    empty_file.write_text("", encoding="utf-8")
    with pytest.raises(ValueError, match="Cookies file is empty"):
        parse_cookies_file(empty_file)

    invalid_json = tmp_path / "invalid.json"
    invalid_json.write_text("{ \"not\": \"a list\" }", encoding="utf-8")
    with pytest.raises(ValueError, match="Invalid cookies format"):
        parse_cookies_file(invalid_json)


def test_format_cookies_for_playwright():
    raw_cookies = [
        {
            "name": "SESSION_A",
            "value": "val_a",
            "domain": "youtube.com",  # Missing leading dot
            "path": "/",
            "expirationDate": 1800000000,
            "sameSite": "no_restriction",
            "secure": 1,
            "httpOnly": 0,
        },
        {
            "name": "SESSION_B",
            "value": "val_b",
            "domain": ".google.com",
            "path": "/sub",
            "expires": "1800000000",
            "sameSite": "strict",
            "secure": True,
            "httpOnly": True,
        },
    ]

    formatted = format_cookies_for_playwright(raw_cookies)
    assert len(formatted) == 2
    assert formatted[0]["domain"] == ".youtube.com"
    assert formatted[0]["sameSite"] == "None"
    assert formatted[0]["expires"] == 1800000000.0
    assert formatted[0]["secure"] is True
    assert formatted[0]["httpOnly"] is False

    assert formatted[1]["domain"] == ".google.com"
    assert formatted[1]["sameSite"] == "Strict"
    assert formatted[1]["expires"] == 1800000000.0


def test_validate_youtube_session_cookies_healthy():
    future_time = time.time() + 86400 * 20
    cookies = [
        {"name": "LOGIN_INFO", "value": "xyz", "expires": future_time},
        {"name": "SID", "value": "sid_val", "expires": future_time},
        {"name": "__Secure-1PSID", "value": "1psid_val", "expires": future_time},
        {"name": "HSID", "value": "hsid_val", "expires": future_time},
        {"name": "SSID", "value": "ssid_val", "expires": future_time},
        {"name": "SAPISID", "value": "sapisid_val", "expires": future_time},
    ]

    result = validate_youtube_session_cookies(cookies)
    assert result.status == SessionStatus.HEALTHY
    assert result.days_left is not None and result.days_left > 19
    assert len(result.missing_tokens) == 0
    assert "activas" in result.detail.lower()


def test_validate_youtube_session_cookies_expiring_soon():
    soon_time = time.time() + 3600 * 24  # 24 hours
    cookies = [
        {"name": "LOGIN_INFO", "value": "xyz", "expires": soon_time},
        {"name": "SID", "value": "sid_val", "expires": soon_time},
        {"name": "__Secure-1PSID", "value": "1psid_val", "expires": soon_time},
    ]

    result = validate_youtube_session_cookies(cookies, expiring_soon_hours=48.0)
    assert result.status == SessionStatus.EXPIRING_SOON
    assert "por expirar" in result.detail.lower() or "restan" in result.detail.lower()


def test_validate_youtube_session_cookies_expired():
    past_time = time.time() - 3600 * 48  # expired 2 days ago
    cookies = [
        {"name": "LOGIN_INFO", "value": "xyz", "expires": past_time},
        {"name": "SID", "value": "sid_val", "expires": past_time},
    ]

    result = validate_youtube_session_cookies(cookies)
    assert result.status == SessionStatus.EXPIRED
    assert "expiradas" in result.detail.lower()


def test_validate_youtube_session_cookies_missing_tokens():
    future_time = time.time() + 86400 * 10
    # Missing LOGIN_INFO and SID
    cookies = [
        {"name": "PREF", "value": "xyz", "expires": future_time},
        {"name": "YSC", "value": "ysc_val", "expires": future_time},
    ]

    result = validate_youtube_session_cookies(cookies)
    assert result.status == SessionStatus.INCOMPLETE
    assert "LOGIN_INFO" in result.missing_tokens
    assert "incompletas" in result.detail.lower() or "faltan" in result.detail.lower()


def test_parse_netscape_cookies_with_httponly_prefix(tmp_path):
    cookie_file = tmp_path / "cookies_httponly.txt"
    future_expiry = int(time.time() + 86400 * 30)
    content = f"""# Netscape HTTP Cookie File
# Generated by curl
#HttpOnly_.youtube.com	TRUE	/	TRUE	{future_expiry}	LOGIN_INFO	tok_httponly_value
#HttpOnly_.google.com	TRUE	/	TRUE	{future_expiry}	SID	sid_httponly_value
.youtube.com	TRUE	/	FALSE	{future_expiry}	PREF	f4=4000000
"""
    cookie_file.write_text(content, encoding="utf-8")

    cookies = parse_cookies_file(cookie_file)
    assert len(cookies) == 3
    login_c = next(c for c in cookies if c["name"] == "LOGIN_INFO")
    assert login_c["httpOnly"] is True
    assert login_c["domain"] == ".youtube.com"
    assert login_c["value"] == "tok_httponly_value"

    health = validate_youtube_session_cookies(cookies)
    assert health.status == SessionStatus.HEALTHY


def test_parse_storage_state_json_dict(tmp_path):
    storage_file = tmp_path / "storage_state.json"
    future_time = time.time() + 86400 * 15
    data = {
        "cookies": [
            {"name": "LOGIN_INFO", "value": "xyz", "domain": ".youtube.com", "expires": future_time},
            {"name": "SID", "value": "abc", "domain": ".google.com", "expires": future_time},
        ],
        "origins": [],
    }
    storage_file.write_text(json.dumps(data), encoding="utf-8")

    cookies = parse_cookies_file(storage_file)
    assert len(cookies) == 2
    assert cookies[0]["name"] == "LOGIN_INFO"


def test_format_cookies_playwright_expires_zero_omitted():
    raw = [
        {"name": "SESSION_COOKIE", "value": "v1", "domain": "youtube.com", "expires": 0},
        {"name": "NEGATIVE_EXPIRY", "value": "v2", "domain": "youtube.com", "expires": -1},
        {"name": "POSITIVE_EXPIRY", "value": "v3", "domain": "youtube.com", "expires": 1800000000},
    ]
    formatted = format_cookies_for_playwright(raw)
    assert "expires" not in formatted[0]
    assert "expires" not in formatted[1]
    assert formatted[2]["expires"] == 1800000000.0


def test_format_cookies_playwright_none_domain_fallback():
    raw = [
        {"name": "COOKIE_NO_DOMAIN", "value": "v1", "domain": None},
        {"name": "COOKIE_EMPTY_DOMAIN", "value": "v2", "domain": ""},
    ]
    formatted = format_cookies_for_playwright(raw)
    assert formatted[0]["domain"] == ".youtube.com"
    assert formatted[1]["domain"] == ".youtube.com"


def test_safe_preupload_failure_classification():
    from src.youtube.uploader import _safe_preupload_failure

    err_expired = RuntimeError("Playwright session validation failed: Cookies expiradas (caducaron hace 2.0 días)")
    err_incomplete = RuntimeError("Playwright session validation failed: Cookies incompletas: falta LOGIN_INFO")
    err_invalid = ValueError("Invalid cookies format in cookies.json")
    err_in_flight = RuntimeError("Upload stuck at 85% after network timeout")

    assert _safe_preupload_failure(err_expired) is True
    assert _safe_preupload_failure(err_incomplete) is True
    assert _safe_preupload_failure(err_invalid) is True
    assert _safe_preupload_failure(err_in_flight) is False


def test_parse_raw_cookie_header(tmp_path):
    from src.core.cookies import parse_raw_cookie_header, save_cookies_to_file
    raw_str = "LOGIN_INFO=token123; SID=sid456; __Secure-3PSID=sec789; PREF=tz=UTC"
    cookies = parse_raw_cookie_header(raw_str)
    assert len(cookies) > 0
    names = {c["name"] for c in cookies}
    assert "LOGIN_INFO" in names
    assert "SID" in names
    # Dual domain check for SID
    sid_domains = {c["domain"] for c in cookies if c["name"] == "SID"}
    assert ".youtube.com" in sid_domains
    assert ".google.com" in sid_domains

    # Test file round-trip
    target_file = tmp_path / "saved_cookies.json"
    save_cookies_to_file(cookies, target_file)
    assert target_file.is_file()
    reloaded = parse_cookies_file(target_file)
    assert len(reloaded) == len(cookies)

